### ISSUE TITLE
BPE code for data preprocessing

### ISSUE THREAD

**Issue by chenyangh** [nlp-dke/NMTGMinor#3]
Hello,

Thanks for sharing the data and code. I wonder is it possible to also share the BPE code that was used to preprocess these datasets? 

Thanks,

**Comment by chenyangh** [comment]
Specifically, I am interested in the BPE code used for the zero-shot NMT project https://github.com/nlp-dke/NMTGMinor/tree/master/recipes/zero-shot

**Comment by dannigt** [comment]
Thanks for reaching out!
The BPE and truecase models have been added [here](https://github.com/nlp-dke/NMTGMinor/tree/master/recipes/zero-shot#download-preprossed-data). 
Note that for PMIndia we used sentencepiece since it better handles tokenization of the Indic languages.

Please feel free to follow up in case of further questions! :)
